### ISSUE TITLE
PHI field is not replaced when inside sequence

### ISSUE THREAD

**Issue by danielsnider** [pydicom/deid#102]
With recipe:
```
REPLACE InstanceCreationDate func:generate_uid
```

The field `InstanceCreationDate` is not replaced when inside of a sequence. See how there are two occurences of InstanceCreationDate and only one got de-identified? My result as seen by `dcmdump`: 

![image](https://user-images.githubusercontent.com/1737560/59978667-c4317580-95ac-11e9-881e-95cb92f8e4ec.png)

What do you think?

Thanks!
Daniel Snider ツ

**Comment by vsoch** [comment]
I think a check needs to be done for a sequence, and if it's a sequence, iterate over it. But that's just me :)

**Comment by vsoch** [comment]
@danielsnider do you have a dummy dicom I can use to test?

**Comment by danielsnider** [comment]
Yes. One minute!

**Comment by danielsnider** [comment]
@vsoch [here](https://sickkidsca-my.sharepoint.com/:u:/g/personal/daniel_snider_sickkids_ca/EU6ypKt3WqdIjEXhWu0mSZQB4pTo-aw0tMCYImOK-9jdTQ?e=hABXMA) you go. Thanks so much.

**Comment by danielsnider** [comment]
It is the DICOM from my example, look for `InstanceCreationDate`.

**Comment by vsoch** [comment]
How do you propose we do this? Currently, it's a matter of looking in the dicom to see if a tag is present. You are asking to additionally parse every tag to check for sequences, and further, to do this recursively. This would hugely slow down the library to need to look everywhere. I don't think this would be feasible, because what if it's a sequence in a sequence? How deep do we go?

Instead, I'd propose that a user can define a nested tag, and that the choice is explicit. So in your case you would need to do:

```
REPLACE ReferencedPerformedProcedureStepSequence.InstanceCreationDate func:generate_uid
```

**Comment by vsoch** [comment]
This library also badly needs pylint, it's driving me nuts just looking at it right now, haha. Based on how easy / hard this fix is, I might pylint first, and maybe create a conda-forge recipe too.

**Comment by danielsnider** [comment]
I would suggest recursing as deep into sequences as possible with a keyword argument to turn it on (or off). I think the importance of finding and removing all PHI outweighs the performance hit of recursing. Computation I think should be sacrificed if it saves human thinking time and increases the quality of de-identification. The added complexity having to know in advance what the full sequence paths to look for is not possible for me because I get a huge variety. I think new users would likely assume that "it just works" ie. `deid` finds all the fields that the user specifies, whether or not inside a sequence. Piece of mind 😊✌.

**Comment by vsoch** [comment]
I'd like to hear others' thoughts on this.

**Comment by vsoch** [comment]
I do agree that removing PHI outweighs performance, but I must stress that deid simply cannot guarantee anything to the user. It's an open source tool that makes a best effort at anonymization. Anyone working with PHI should never have peace of mind, but rather a piece of their mind always worrying and then double checking. :)

**Comment by danielsnider** [comment]
Haha. So true!! Well put.

**Comment by danielsnider** [comment]
Hi @vsoch, Think you could point me to the line of code where I might start implementing recursing into sequences? There is some urgency 🦁

**Comment by vsoch** [comment]
There’s already a function that is called by get_fields (I think in dicom.fields) to expand sequences, and a Boolean somewhere to control it at entry to one of the functions in header. It’s getting late here so I’m done for today, but I’d you can wait until tomorrow morning I can start this for you. This afternoon I was able to add pylint and create a conda staged recipe, so I’m happy to move on to next step.

Everything is always urgent @danielsnider, when we don’t feel urgency I think we’ll be pushing daisies.

**Comment by danielsnider** [comment]
@vsoch Give it a start if can 🤩. Night! 
I'm prepping my server to ElasticSearch server receive and index 100 million dicoms from this `deid` package!! 🎉

**Comment by danielsnider** [comment]
Bring on the recursion and it's performance hit. We have 15,000 CPUs! 😎!
