### ISSUE TITLE
Create python wheel

### ISSUE THREAD

**Issue by Spenhouet** [pydicom/deid#108]
I have the same issue as: https://github.com/pydicom/deid/issues/97
But I don't want to install Anaconda and I could not resolve the issue.
I already installed libpng and FreeType, also added them to the paths. The files that the error message claims are missing are actually on the path... so I don't get what the issue is.

From this issue (https://github.com/matplotlib/matplotlib/issues/13553) I gathered that if you would provide a "wheel" (https://pythonwheels.com/) this issue would be solved for everyone.
Many packaged create these wheels, for example matplotlib here: https://pypi.org/project/matplotlib/#files

About wheels from the link above:

> **What are wheels?**
> Wheels are the new standard of Python distribution and are intended to replace eggs. Support is offered in pip >= 1.4 and setuptools >= 0.8.
> 
> **Advantages of wheels**
> - Faster installation for pure Python and native C extension packages.
> - Avoids arbitrary code execution for installation. (Avoids setup.py)
> - Installation of a C extension does not require a compiler on Linux, Windows or macOS.
> - Allows better caching for testing and continuous integration.
> - Creates .pyc files as part of installation to ensure they match the Python interpreter used.
> - More consistent installs across platforms and machines.

Would this be possible?

**Comment by vsoch** [comment]
You can easily do this on your host https://stackoverflow.com/questions/26059111/build-a-wheel-egg-and-all-dependencies-for-a-python-project.

**Comment by Spenhouet** [comment]
Wouldn't I run into the same issue with libpng and FreeType?

**Comment by vsoch** [comment]
Did you try it? I'm not sure, I've never needed to do this.

**Comment by vsoch** [comment]
What version of Python are you using? Is this somehow related to python 2 to 3?

**Comment by Spenhouet** [comment]
I'm using python 3.7.5 64 bit.

From what I understand the whole idea behind these wheels is that other people who want to use your package don't need to build C extensions you used. That is why I asked if you could provide the wheels. I'm not sure how much work that is :/ but it definitely would be more convenient for every Windows user who would not need to fight with these issues.

**Comment by vsoch** [comment]
Ah, it must be a Windows thing. Ok - so you are going to be my first tester (I've never distributed a wheel before, just eggs). Take a look here, there should be a wheel. https://pypi.org/project/deid/0.1.34/#files I'm concerned about the "none" (I just did a quick sdist for the wheel generation) and it could be that I need to specify OS. See if you can use that, and if not, let's chat about how to generate and then use.

**Comment by Spenhouet** [comment]
I tested the file but it resulted in the same issue.

The tricky (and probably time consuming) part seems to be that you have to build the C extensions on the target OS and build the wheels on the target OS/python version.

> **C extensions**
> PyPI currently allows uploading platform-specific wheels for Windows, macOS and Linux. It is useful to create wheels for these platforms, as it avoids the need for your users to compile the package when installing.
> 
> You will need to have access to the platform you are building for.

For bigger organisations with multiple build machines that is an easy task but if you have only access to a Linux machine and to create these wheels you would need to setup all these systems with... I feel like that is too much to expect.

But still, thank you for your very fast reply!

I'm still not sure why the installation isn't able to find the C headers (that are on the path). I did see many similar issues / threads on different repositories, so it seems to be a very common problem for Windows user. But I did not yet find a plausibly / good solution.
I will investigate tomorrow.

**Comment by vsoch** [comment]
I don't have a Windows machine, but I suspect it's the same issue that you'd see on Linux, either when something isn't on the LD_LIBRARY_PATH (or Windows equivalent) or just the PATH, or it's not exported, or the user hasn't run ldconfig. I don't have expertise with Windows for more than 10 years now and I also don't have a Windows machine to play around with, so I'm afraid my ability to help is limited. What you could try doing is writing a build recipe (GitHub action, or CircleCI) to build the wheel. If you get something working, we could try to package it here. Other than that, I think I'm out of ideas! I'll leave the issue open in case others have thoughts.

**Comment by Spenhouet** [comment]
Okay, so I have no progress on the path issue but I now know more about my issue.

In the package version requirements you did limit the matplotlib version to max 2.1.2.
The issue is, that matplotlib 2.1.2 only has wheels up until python 3.6 but not for 3.7 and 3.8.
Therefore the installation is failing.
Upgrading matplotlib in the deid package to a newer version (3.1.2 for example) would solve this issue.
I did so manually (changed `('matplotlib', {'max_version': '2.1.2'})` to `('matplotlib', {'min_version': None})` and the installation did run through without problem.
I did not test and don't know if the package is working as intended and without errors (since it is now used with a much newer matplotlib version than specified.

**Comment by vsoch** [comment]
Interesting! At least there is a fix / workaround. For matplotlib, it's been a while but I remember needing to pin the version for some reason. In the CHANGELOG I see:

> matplotlib must be less than or equal to 2.1.2 for install (0.1.16)

and then in commit history:

> :9c44fd2d53d2d52e0ee2821c762df50d76d99f70 3d684e3254e0019dbeae597ee59c84cd1eb1a665 vsoch <vsochat@stanford.edu> 1504414437 -0400	commit: matplotlib imports should be within function -issue with headless

here -> https://github.com/pydicom/deid/commit/3d684e3254e0019dbeae597ee59c84cd1eb1a665#diff-1bc0aa28eb3b1837a500e2553978cb34R70

Since you've installed with later, if you want to try running tests, and generally using the library on your host (and see if you run into issues) this would at least be helpful to understand if anything is broken.

**Comment by vsoch** [comment]
I would actually hope that we find an issue with the newer version, and then possibly a fix so that the version can be updated.

**Comment by Spenhouet** [comment]
I can't promise that we will end up using deid, but I will let you know.
If we do, I will report back any issues I encounter.

**Comment by vsoch** [comment]
Any updates @Spenhouet ?

**Comment by Spenhouet** [comment]
It seem like we will go about anonymization by simply not transmitting DICOMs at all and only transferring image data (NIfTI).

Thanks for pinging me and sorry for my late reply.
