### ISSUE TITLE
Update version of Matplotlib 

### ISSUE THREAD

**Issue by davidparsson** [pydicom/deid#109]
Is there a particular reason behind the specified max version of matplotlib requred?

I'm trying to install this in a project that's using a newer version of matplotlib, and a dependency management tool that does not allow version mismatches.

Thanks!

**Comment by vsoch** [comment]
There was a particular reason - but I didn't document it and I can't remember. I think it had something to do with the cleaning of pixels functionality, and some function afforded by previous versions of matplotlib.

Would you care to remove the version dependency, and test out the library, and report back any issues?

**Comment by davidparsson** [comment]
I don't really have a lot of time, nor deid experience, but if I find the
time I might give it a try.

Den fre 7 feb. 2020 kl 23:23 skrev Vanessasaurus <notifications@github.com>:

**Comment by vsoch** [comment]
hey  @davidparsson I'll see if I can make this slightly easier for you with a branch that explicitly removes the version dependency. Give me a little bit and I'll push - also going to add black for formatting and a few (non functional change) updates.

**Comment by vsoch** [comment]
okay just hit the error with local testing - a deprecated key "scale"
```
======================================================================
ERROR: test_add_tag (test_dicom_tags.TestDicomTags)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/vanessa/Desktop/Code/deid/deid/tests/test_dicom_tags.py", line 49, in test_add_tag
    from deid.dicom.tags import add_tag
  File "/home/vanessa/Desktop/Code/deid/deid/dicom/__init__.py", line 12, in <module>
    from .pixels import has_burned_pixels, DicomCleaner
  File "/home/vanessa/Desktop/Code/deid/deid/dicom/pixels/__init__.py", line 2, in <module>
    from .clean import DicomCleaner
  File "/home/vanessa/Desktop/Code/deid/deid/dicom/pixels/clean.py", line 34, in <module>
    matplotlib.use("pdf")
  File "/home/vanessa/anaconda3/lib/python3.7/site-packages/matplotlib-3.2.0rc3-py3.7-linux-x86_64.egg/matplotlib/cbook/deprecation.py", line 296, in wrapper
    return func(*args, **kwargs)
  File "/home/vanessa/anaconda3/lib/python3.7/site-packages/matplotlib-3.2.0rc3-py3.7-linux-x86_64.egg/matplotlib/cbook/deprecation.py", line 358, in wrapper
    return func(*args, **kwargs)
  File "/home/vanessa/anaconda3/lib/python3.7/site-packages/matplotlib-3.2.0rc3-py3.7-linux-x86_64.egg/matplotlib/__init__.py", line 1253, in use
    from matplotlib import pyplot as plt
  File "/home/vanessa/anaconda3/lib/python3.7/site-packages/matplotlib-3.2.0rc3-py3.7-linux-x86_64.egg/matplotlib/pyplot.py", line 40, in <module>
    from matplotlib.figure import Figure, figaspect
  File "/home/vanessa/anaconda3/lib/python3.7/site-packages/matplotlib-3.2.0rc3-py3.7-linux-x86_64.egg/matplotlib/figure.py", line 20, in <module>
    from matplotlib import backends, docstring, projections
  File "/home/vanessa/anaconda3/lib/python3.7/site-packages/matplotlib-3.2.0rc3-py3.7-linux-x86_64.egg/matplotlib/projections/__init__.py", line 4, in <module>
    from mpl_toolkits.mplot3d import Axes3D
  File "/home/vanessa/anaconda3/lib/python3.7/site-packages/mpl_toolkits/mplot3d/__init__.py", line 1, in <module>
    from .axes3d import Axes3D
  File "/home/vanessa/anaconda3/lib/python3.7/site-packages/mpl_toolkits/mplot3d/axes3d.py", line 42, in <module>
    class Axes3D(Axes):
  File "/home/vanessa/anaconda3/lib/python3.7/site-packages/mpl_toolkits/mplot3d/axes3d.py", line 52, in Axes3D
    azim=-60, elev=30, zscale=None, sharez=None, proj_type='persp',
  File "/home/vanessa/anaconda3/lib/python3.7/site-packages/matplotlib-3.2.0rc3-py3.7-linux-x86_64.egg/matplotlib/docstring.py", line 116, in dedent_interpd
    return interpd(func)
  File "/home/vanessa/anaconda3/lib/python3.7/site-packages/matplotlib-3.2.0rc3-py3.7-linux-x86_64.egg/matplotlib/docstring.py", line 40, in __call__
    func.__doc__ %= self.params
KeyError: 'scale'

----------------------------------------------------------------------
Ran 18 tests in 0.675s

FAILED (errors=1)

```

**Comment by vsoch** [comment]
Triggered from calling `matplotlib.use("pdf")`

**Comment by davidparsson** [comment]
Ok, thank you!

Do you know if there's a way around that issue, or if deid will be stuck on
this version?

**Comment by vsoch** [comment]
I would say with some confidence that it can be fixed, if someone can put in the time to test some workarounds.

For you and others interested in debugging this issue, I've created a starting branch that again restates the error:

https://github.com/pydicom/deid/pull/111

I've also added the help wanted label to this issue.

**Comment by vsoch** [comment]
Some possible things to look into:

 - if the syntax / way of using the pdf backend has changed
 - if there is a system dependency missing (and it's a silent / misleading error)
 - if others have encountered this, of course.
 - why the KeyError is for scale

**Comment by davidparsson** [comment]
All right, that's reasonable. Thank you!

**Comment by vsoch** [comment]
hey @davidparsson good news! I gave this another look over with fresh eyes, and it looks like the matplotlib issue was something on my system - when I removed and reinstalled with pip the tests pass! I've updated the PR, so now you should be able to clone and install this branch, and take it for a spin to see if any issues are reproduced. https://github.com/pydicom/deid/pull/111

**Comment by vsoch** [comment]
hey @davidparsson any updates on being able to test the PR? I also wanted to get your feedback on using matplotlib-base [see the conda suggestion here](https://github.com/conda-forge/deid-feedstock/pull/4)! Would you have time in the coming future to test either of these for your use case?

**Comment by davidparsson** [comment]
Nope, sorry @vsoch! I gave it a quick look but got stuck since I didn't have any test data that could trigger the behavior. Do you have any at hand?

If I'm not able to get this done during the weekend it will likely be a week or two before I can spend some more time on it.

**Comment by vsoch** [comment]
That's totally ok! There is definitely no rush - when you have some time~

**Comment by davidparsson** [comment]
Ok, I'm ready to dig into this. However, as a complete newbie on `deid` I don't really have any clue on what is needed to reproduce this, both in terms of DICOM data and configuration, and when that's done I'm not entirely sure what to look for either. If you're able to provide me with some pointers, I'd really appreciate it, and if not I'll have to manage anyway.

**Comment by vsoch** [comment]
The best thing to do I think is to follow the getting started guide, and walk through some of the examples and ensure that everything works okay. Have you seen the docs at https://pydicom.github.io/deid/getting-started/index.html ?

**Comment by davidparsson** [comment]
Thanks, I'll give it a shot!

**Comment by vsoch** [comment]
Thank you!

**Comment by davidparsson** [comment]
@vsoch, I have not been able to find any issues on this branch.

**What I have done is:**

1. Create a recipe that cleans a few pixels in a DICOM image
2. Create a Docker image from this branch
3. Clean a DICOM file using the image and recipe, and saving the result both as `.dcm` and `.png`.
4. Compared the results from the same recipe but with the image `pydicom/deid:latest`.

**Findings:**

The `.dcm` files are binary identical. The `.png` files are not binary identical, but I cannot see any differences in the images when carefully inspecting them.

**Conclusion:**

It should be safe to remove the max version limit on matplotlib.

**Comment by davidparsson** [comment]
Do you think any further investigations are needed? If not, can I expect a release without the matplotlib version restriction any time soon?

Thank you!

**Comment by vsoch** [comment]
I'm in agreement. I'll move forward with merging and releasing. Thanks for testing @davidparsson !

**Comment by vsoch** [comment]
Thank you for your help with this @davidparsson ! There should be two releases you can choose from now, the first with >= and the second with the dependency lifted. Please open another issue if you run into trouble with this change.

**Comment by davidparsson** [comment]
Thanks!

Regarding this:
> I also wanted to get your feedback on using matplotlib-base [see the conda suggestion here](https://github.com/conda-forge/deid-feedstock/pull/4)!

I don't know enough about matplotlib/matplotlib-base/conda to give any useful feedback.
