### ISSUE TITLE
Is this project still active?

### ISSUE THREAD

**Issue by guillego** [pydicom/deid#139]
Deid requires pydicom == 1.3.0 which is a major version behind the current 2.0.0, are there any plans to bring it to current compatibility?

**Comment by vsoch** [comment]
I believe it was pinned for the Dicom cleaner, there isn’t any reason (I don’t think) you couldn’t use a newer version of pydicom, but it would need to be tested. If you want to install it alongside 2.0.0 and give it for a spin (and provide feedback) Is be happy to officially update.

**Comment by vsoch** [comment]
ping @guillego would you care to test this? Otherwise, I'll close the issue as I think I answered your question.
