### ISSUE TITLE
Image mask verification for graylist images

### ISSUE THREAD

**Issue by regoldman** [pydicom/deid#15]

**Comment by vsoch** [comment]
Graylist means we have identified an image that we know the pixel coordinates of the PHI, and we can replace. So this is referring to a validation of a method to:

 - produce a set of graylist images
 - perform masking on known coordinates
 - visually verify accuracy, including accuracy of boxes (coordinates), along with images that were not flagged with graylist. Eg: both graylist and not graylist accuracy (FP,FN,TP,TN), and then within graylist, accuracy of mask.
