### ISSUE TITLE
bot.level set to 3 when importing DeidRecipe

### ISSUE THREAD

**Issue by skarrea** [pydicom/deid#158]
When trying to suppress the error message mentioned in #157 I noticed that `bot.level = 3` is assigned in line 38 of [deid/deid/config/\_\_init\_\_.py](https://github.com/pydicom/deid/blob/master/deid/config/__init__.py). Thus regardless of the specified `MESSAGELEVEL`  in the environment variables which is used in the [DeidMessage class](https://github.com/pydicom/deid/blob/master/deid/logger/message.py) the bot will change to level 3 when importing [DeidRecipe](https://github.com/pydicom/deid/blob/master/deid/config/__init__.py).

### Reproducing the behavior:

This code reproduces the aforementioned behavior:

```
import contextlib
import os

@contextlib.contextmanager
def set_env(**environ):
    """
    Temporarily set the process environment variables.

    >>> with set_env(PLUGINS_DIR=u'test/plugins'):
    ...   "PLUGINS_DIR" in os.environ
    True

    >>> "PLUGINS_DIR" in os.environ
    False

    :type environ: dict[str, unicode]
    :param environ: Environment variables to set

    from:
    https://stackoverflow.com/questions/2059482/python-temporarily-modify-the-current-processs-environment
    """
    old_environ = dict(os.environ)
    os.environ.update(environ)
    try:
        yield
    finally:
        os.environ.clear()
        os.environ.update(old_environ)

with set_env(MESSAGELEVEL="5"):
    from deid.logger import bot
    print(bot.level)
    from deid.config import DeidRecipe
    print(bot.level)
```
### Output
```
bot.level before import: 5
bot.level after import: 3
```

**Comment by vsoch** [comment]
@skarrea would you like to just remove that line? That would respect the user-set level. And for #157 - another idea is to remove that line all-together, or put it at a higher level where it's needed (perhaps get/set identifiers). Would that work for a fix?

**Comment by vsoch** [comment]
Please see https://github.com/pydicom/deid/pull/159 as a suggested solution.

**Comment by skarrea** [comment]
Yes, that is perfect!
