### ISSUE TITLE
OCR for blacklist images

### ISSUE THREAD

**Issue by regoldman** [pydicom/deid#16]

**Comment by vsoch** [comment]
Note that I started a project that aims to do this - https://github.com/pydicom/dicom-scraper

This would be a prime project for a graduate student or similar - it's well scoped machine learning, with plenty of data for development. @regoldman do you have a pool (or can announce at some meeting the need) for a graduate student that might be interested? I can offer to container-ize / tool-ize a suitable algorithm that the graduate student develops. The one I started might also be tweaked tested, my general feeling is that the kind of OCR we need isn't terribly "unsolved" in the scope of problems.

**Comment by danielsnider** [comment]
Hi @vsoch I am working on this ;-). I also have grad students that might join. I'll give you an update in a week and then lets chat.

**Comment by vsoch** [comment]
This is out of scope for deid (and no discussion has happened for about a year) so closing issue.
