### ISSUE TITLE
Documentation : Recipe Labels title

### ISSUE THREAD

**Issue by vpapaioannou** [pydicom/deid#162]
Documentatoin https://pydicom.github.io/deid/user-docs/recipe-labels/ shouldn't have 'Recipe Labels' instead of 'Recipe Headers'?

Thanks.

**Comment by vsoch** [comment]
Good catch, thanks! It should be updated after GitHub pages re-renders, and of course the browser cache is off.

**Comment by vpapaioannou** [comment]
Btw, would you like me to tell you that kind of stuff? I saw few more but I don't want to bother you.

**Comment by vsoch** [comment]
Most definitely! And here is an idea - if you want to work on a single PR to update the docs, maybe take a few days as you are using deid to catch issues, if it's substantial fixes I'd be happy to receive the PR and give you a Hacktoberfest credit for it.

**Comment by vpapaioannou** [comment]
Sounds good.
