### ISSUE TITLE
Dependence `pydicom` version too low

### ISSUE THREAD

**Issue by dipterix** [pydicom/deid#171]
Thanks for developing such great package! 

I was experimenting with DICOM editing the other day. However, I encountered problem when converting DICOM from `YBR_FULL_422` to RGB color space. This feature has been added to `pydicom` since version 1.4, but `deid` still requires `pydicom=1.3`.

I resolve the issue by forcing pip to install the newest version of pydicom. However, I still want to ask is there any reason not to bump the version requirement, like incompatibility issues? 

Thanks :)

**Comment by vsoch** [comment]
Yes that would work! If you'd like to open a PR I can review it. We would want to bump the version of deid (deid/version.py) and add a note to the change log.

**Comment by vsoch** [comment]
Ping @dipterix !

**Comment by wetzelj** [comment]
For what it's worth - we've been using pydicom 2.1.1 with deid for several months now and have not experienced any issues.  @dipterix , @vsoch - Do you want me to create this PR?  If so, I see that version 2.1.2 has been released.  While we haven't been testing/using this version do you want me to move pydicom to 2.1.2 or set it to what I can comfortably say has been tested (2.1.1)?

**Comment by vsoch** [comment]
@wetzelj let's set it to the version that has been tested. If you have bandwidth, a PR would be great! I would have time over the weekend.

**Comment by dipterix** [comment]
Thanks @wetzelj , I'm not that familiar with python. It'll be great if you can help :)

**Comment by vsoch** [comment]
@dipterix this is merged into the master branch and will be available with the next release! :partying_face: we have a few other bug fixes coming in soon.

**Comment by vsoch** [comment]
Going to close here since it's addressed - look out for a release in the next few days (or just use master!)
