### ISSUE TITLE
Adding Multivalued Fields to %values Lists

### ISSUE THREAD

**Issue by wetzelj** [pydicom/deid#174]
When fields specified within recipe file %values lists contain a list of items, the addition of the Multi-value value to the values array causes an exception (Exception: unhashable type: 'MultiValue').  

I believe that this can be corrected checking the type of the value first - if it is [MultiValue](https://pydicom.github.io/pydicom/stable/reference/generated/pydicom.multival.MultiValue.html#pydicom.multival.MultiValue), we can use set.Update() to update the values list instead of using set.Add().  

I've committed a possible fix to the [wetzelj/deid INFOR-831](https://github.com/wetzelj/deid/tree/fix/INFOR-831) branch.

**Comment by vsoch** [comment]
@wetzelj let's take these one by one! If there are easy fixes (like the one) let's do a PR from your branch and bumping the version. More complex issues (or ones you want my help with) I could take a look in an evening or weekend.

**Comment by wetzelj** [comment]
@vsoch Sounds good... it's on its way

**Comment by vsoch** [comment]
This is all set.
