### ISSUE TITLE
Date Jitter on %values Lists

### ISSUE THREAD

**Issue by wetzelj** [pydicom/deid#175]
During the deidentification of a study a situation was encountered where the StudyDate value existed within a private dicom tag.  This tag (0029,1019) was of data type LO, but contained the StudyDate value:

```(0029,1019) : LO   Len: 8 <Unknown Tag> Value: [20100526]```
We attempted to handle this using current recipe functionality:
```
%values testing 
FIELD StudyDate 
%header 
JITTER values:testing -3241
```
However, performing these actions did not jitter the value in the Private tag.
 
**Root Cause**
pydicom/deid (deid\dicom\actions.py - jitter_timestamp())
This function expressly performs JITTER only if the DICOM VR is DT or DA.
 
**Idea**
Figure out how to handle non-date typed values.  We could attempt to parse the string representations of the [DA/DT types](http://dicom.nema.org/dicom/2013/output/chtml/part05/sect_6.2.html), and if it doesn't produce an exception, jitter it.

**Comment by vsoch** [comment]
This is closed by #181
