### ISSUE TITLE
Update lunr.min.js?

### ISSUE THREAD

**Issue by DimitriPapadopoulos** [pydicom/deid#188]
Just wondering why the version of [Lunr](https://lunrjs.com/) used here is [0.7.0 from 2016](https://github.com/pydicom/deid/blob/04dc088/docs/assets/js/lunr.min.js#L2-L3), while the current version is [2.3.9 from 2020](https://github.com/olivernn/lunr.js/tags).

**Comment by vsoch** [comment]
Is there something wrong with the old one?

**Comment by DimitriPapadopoulos** [comment]
Well, the truth is I haven't found vulnerabilities associated to Lunr. But if there are, at some point, upgrading will be much more difficult.

**Comment by vsoch** [comment]
I'm totally good with upgrading if there is a good reason, but I don't see one here.
