### ISSUE TITLE
Exception when JITTER performed on empty field

### ISSUE THREAD

**Issue by wetzelj** [pydicom/deid#189]
When a JITTER rule is performed on a header field which contains an empty string rather than a DICOM formatted date/timestamp value, an exception occurs, stopping the deidentification of the header.

Cause: 
-  On [parser.py line 467](https://github.com/pydicom/deid/blob/d57287048f747c5ea2fa67f2f3889c8758d16df1/deid/dicom/parser.py#L467), jitter_timestamp() is called to obtain the new value for the timestamp field.  This function then calls get_timestamp(), which actually calculates the new value.  In get_timestamp(), if the value is "" or None, the new value returned is None. 
- Subsequently, on [parser.py line 468](https://github.com/pydicom/deid/blob/d57287048f747c5ea2fa67f2f3889c8758d16df1/deid/dicom/parser.py#L468), replace_field() is called with the new "None" value.  Within replace_field, we eventually get to the parse_field() method.  Parse field attempts to perform a regex search (to look for potential expanders) on the None value, causing the exception.

Proposed Fix: 
- For JITTER actions, check the new value returned for the field.  Only call replace_field if the value is not None.  (pull request coming shortly)

**Comment by vsoch** [comment]
Sounds good!
