### ISSUE TITLE
pydicom bump to 2.2.2 ?

### ISSUE THREAD

**Issue by glebsts** [pydicom/deid#193]
Hello,
Thank you for this package. I am evaluating it for my needs.
I can see from `pydicom` changelog, that it has some new bugfixes and additions ([changelog](https://github.com/pydicom/pydicom/releases))
How hard would it be to bump `pydicom` to latest `2.2.2`? What tests must be made and could I contribute this change?

**Comment by vsoch** [comment]
If you’d like to bump the version and open a PR we can test. Thanks!
