### ISSUE TITLE
FairShare Specification/Implementation

### ISSUE THREAD

**Issue by regoldman** [pydicom/deid#20]

**Comment by vsoch** [comment]
Is this what you mean? --> http://docs.adaptivecomputing.com/9-0-3/MWM/Content/topics/moabWorkloadManager/topics/fairness/fairshare.html Could you tell me more?

**Comment by vsoch** [comment]
I'm not sure this is relevant to this resource - it sounds more appropriate for the pipeline / infrastructure that is using deid. Closing, please re-open if there is issue and/or to provide more detail.
