### ISSUE TITLE
Keeping up-to-date with CTP

### ISSUE THREAD

**Issue by howff** [pydicom/deid#200]
Hi

Are you keeping up-to-date with the CTP anonymiser script, which is here?
https://github.com/johnperry/CTP/blob/master/source/files/scripts/DicomPixelAnonymizer.script

The reason I ask is because your doc references this one
https://github.com/johnperry/CTP/blob/8a3c595b60442e6d74aec4098eaed5dcf8ff8770/source/files/examples/example-dicom-pixel-anonymizer.script
which is just an example, and out of date.

Also, are you intending to keep the same rules or do you have any additional rules that CTP doesn't have?

Thanks!

**Comment by vsoch** [comment]
I am not actively doing so, but I agree that we should. Would this be something you are interested in contributing?

**Comment by howff** [comment]
I might do, but I fear that the two have already diverged and it would be difficult for me to know how to get them reconciled.

**Comment by vsoch** [comment]
I mean, it comes down to getting the latest file for CTP, and comparing that to what we have here - it's a pretty simple task. if you are not up to it, if you want to provide me a link to the latest file I will volunteer my time.

**Comment by howff** [comment]
The link is in my first comment above.  It's in the directory https://github.com/johnperry/CTP/tree/master/source/files/scripts

It's also in your document https://pydicom.github.io/deid/getting-started/dicom-pixels/#inspiration-from-ctp
(good docs, by the way)

I hesitate to do it myself because it looks as though the pydicom syntax for this script is different, and the rules have been modified compared to the ctp version, so I don't want to break anything.

Anyway you can see the commits to the CTP script here
https://github.com/johnperry/CTP/commits/master/source/files/scripts/DicomPixelAnonymizer.script
Maybe there's only a couple of commits which need to be incorporated into pydicom.

**Comment by vsoch** [comment]
Ah fantastic idea! I'll try to make some time in evenings this week. Thank you @howff.

**Comment by vsoch** [comment]
okay there aren't that many changes - will have a PR for you to review this evening.

**Comment by vsoch** [comment]
Here you go! https://github.com/pydicom/deid/pull/202

**Comment by howff** [comment]
Fantastic, thank you :-) 🥇

**Comment by vsoch** [comment]
Let me know when you've had a chance to review, and the changes look good to merge.
