### ISSUE TITLE
Replace tags with VR PN in recipe

### ISSUE THREAD

**Issue by NirutaDhimal** [pydicom/deid#219]
Is there a way to replace only the tags with Value Representation "PN" using recipe?

**Comment by vsoch** [comment]
Not yet, but this will be supported with https://github.com/pydicom/deid/pull/215

**Comment by vsoch** [comment]
hey @NirutaDhimal ! This was just merged. See this page, https://pydicom.github.io/deid/user-docs/recipe-headers/ 

Sections -> Header -> Select

and that is the syntax you can use to select VR tags 

![image](https://user-images.githubusercontent.com/814322/192174726-8a951c72-75a9-4aca-8a06-d3c1d4421459.png)

So I think you could do either of the following to blank (replace with nothing) or replace:

```
BLANK select:VR:PN
REPLACE select:VR:PN <another-thing>
```
Pinging @jstorrs in case there is further discussion!

**Comment by NirutaDhimal** [comment]
Thank you. It's working .

**Comment by vsoch** [comment]
Woohoo! Great to hear - giving a shoutout to @jstorrs that just added this feature (good timing too!) Closing issue.
