### ISSUE TITLE
How can I get the value of a tag each dicom files in get_identifiers?

### ISSUE THREAD

**Issue by NirutaDhimal** [pydicom/deid#220]
How can I get the value of a tag of each dicom files in get_identifiers?

**Comment by vsoch** [comment]
That function returns a dictionary that has all fields -> values. https://pydicom.github.io/deid/examples/func-replace/

**Comment by NirutaDhimal** [comment]
Hi, can you please specify which function? The above link took me to examples section

**Comment by vsoch** [comment]
Look on that page at:

```
items = get_identifiers(dicom_files, expand_sequences=True)
```
and see the example output below it. Try running it on your own to see the same.

**Comment by NirutaDhimal** [comment]
Thanks

**Comment by vsoch** [comment]
Sure thing! Closing, ping again if you need.

**Comment by NirutaDhimal** [comment]
I tried to implement 
items = get_identifiers(dicom_files, expand_sequences=True)
but I am getting error
![newerr1](https://user-images.githubusercontent.com/58328226/192723354-6c48f908-cf7c-4b37-98de-686172505990.png)
![newerr2](https://user-images.githubusercontent.com/58328226/192723404-26fcb2f2-c13c-44a1-ae84-1f824a2b6354.png)

**Comment by vsoch** [comment]
Sorry about that must be a typo - the function has `strip_sequences` and not `expand_sequences`! https://github.com/pydicom/deid/blob/b1556a72c9fbfbfb7967da774e67057f7c437a02/deid/dicom/header.py#L25

**Comment by vsoch** [comment]
And actually, it's a bug! It should be there - it was erroneously removed. I'll get a PR in to fix it asap!

**Comment by vsoch** [comment]
ok it's fixed! If you are using the older version the default for expand_sequences (internal to the function) is True, so safe to just move it from the above. Thanks for catching the error!
