### ISSUE TITLE
Save files in a fixed naming format

### ISSUE THREAD

**Issue by NirutaDhimal** [pydicom/deid#221]
After the replace_identifiers function is executed the files are stored in a format "PatientID_SOPInstanceID". But I want to store the file in this format "mask_modality_studyDate_instancenumber". here mask is the value that I replaced patientID with. 
How can I do this?

**Comment by vsoch** [comment]
Save accepts a filename https://deid.readthedocs.io/en/latest/source/deid.dicom.html?highlight=save#deid.dicom.parser.DicomParser.save.

**Comment by NirutaDhimal** [comment]
I am using replace_identifiers function. Is there a way for me to save the files in above naming pattern?

**Comment by vsoch** [comment]
Through that interface, I would set `output_folder` from `None` to a temporary directory, and then rename them after to whatever you'd like.

**Comment by NirutaDhimal** [comment]
Thanks
