### ISSUE TITLE
Really heavy package

### ISSUE THREAD

**Issue by RobinFrcd** [pydicom/deid#225]
Hello,
I realized that the package is quite big (**27.2 MB** for the .tar.gz), would it be possible to lighten it ?

I assume the culprit here are the `.dcm` in the [data folder](https://github.com/pydicom/deid/tree/master/deid/data). This folder is only used for tests, right ? Would it be possible to move the tests and tests data out of the package folder in order not to ship it during the build ?

Thanks :pray:

**Comment by vsoch** [comment]
Agree! There is already an issue for this, but nobody has worked on it yet. https://github.com/pydicom/deid/issues/167 Ping @wetzelj to see if there is still interest. Closing here and we can continue conversation in https://github.com/pydicom/deid/issues/167
