### ISSUE TITLE
get skull pixel data 

### ISSUE THREAD

**Issue by NirutaDhimal** [pydicom/deid#229]
I am trying to mask everything outside skull region in brain. Is there a way I specify skull in the recipe without having to give the actual coordinates?

**Comment by vsoch** [comment]
Are you using fMRI or nifti? If you are using dicom from brain imaging your best bet is to use more well established tools like FSL, SPM, or AFNI especially for masking. The tools here are primarily for other dicom like CT and ultrasound.

**Comment by vsoch** [comment]
Take a look at BET in FSL as a good start.

**Comment by NirutaDhimal** [comment]
Thank you. I am using dicom for brain imaging

**Comment by vsoch** [comment]
Gotcha! So I’d check out those software suites and the nipy suite of tools. Most convert dicom to nifti and go from there.

**Comment by NirutaDhimal** [comment]
Thanks. Is there a way to mask everything outside skull in deid module or to get the skull pixels?

**Comment by vsoch** [comment]
That’s what a tool like BET is for.

**Comment by NirutaDhimal** [comment]
Got it. Thanks for the help

**Comment by NirutaDhimal** [comment]
Can I ask you something? I may sound stupid. What are we anonymizing while cleaning pixel data? Are we just removing the annotations?

**Comment by vsoch** [comment]
Yes exactly. For modality like CT and ultrasound patient personal information and metadata is often burned into the images, and the machines do it in predictable locations so we can erase it. That’s also more typical in a clinical context so the images have patient information. At least for brain imaging studies, if there are any burnt pixels (it’s been a long time but I don’t remember the post processed nifti shaving them) they would be removed in the analysis pipeline in an early step when you generate a brain mask.

If you are new to brain imaging the community is hugely active and vibrant and there are a ton of tools and methods for learning! Generally pydicom and deid are more catered toward clinical CT and ultrasound (and similar) and the communities overlap but I think it’s a bit smaller than neuroimaging primarily.

**Comment by NirutaDhimal** [comment]
Thank you so much. It's really helpful and I am new to medical images.

**Comment by vsoch** [comment]
Sure thing! Good luck and have fun. The tools are very good - most have both command line and GUI interfaces and pipelines (check out nipype for example) so you can script or click through multiple pipelines very easily. My biggest advice is to make sure to look at your data every step of the way, and (at least when I was learning) I liked to try something in a GUI first and then reproduce on the command line to run automated on many more subjects, usually on HPC.

**Comment by vsoch** [comment]
Going to close this @NirutaDhimal - thanks for stopping by!
