### ISSUE TITLE
ImportError: cannot import name 'clean_pixel_data' from 'deid.dicom.pixels'

### ISSUE THREAD

**Issue by NirutaDhimal** [pydicom/deid#233]
I am trying to import clean_pixel_data from deid.dicom.pixels but I got the importError.
And a quick question, Is it better to use DicomCleaner or clean_pixel_data while implementing multithreading?
![eer1](https://user-images.githubusercontent.com/58328226/194702156-ffb8d23c-16bf-4d46-a155-770165474e95.png)
![eer2](https://user-images.githubusercontent.com/58328226/194702172-02115a2d-9979-4260-abec-811190ced06f.png)

**Comment by vsoch** [comment]
What exactly is the error? I cannot reproduce.

**Comment by NirutaDhimal** [comment]
Its an ImportError: cannot import name 'clean_pixel_data' from 'deid.dicom.pixels'

**Comment by vsoch** [comment]
okay - so look in the content of `deid/dicom/pixels/__init__.py` what is there?

**Comment by vsoch** [comment]
I'm wondering if it's about your install or environment, because here is the import for me:

![image](https://user-images.githubusercontent.com/814322/194705298-3dac1d19-5ee3-4345-975f-0e30d1b11c8a.png)

**Comment by NirutaDhimal** [comment]
This is the content of __init__.py. It doesn't have clean_pixel_data.
![eer3](https://user-images.githubusercontent.com/58328226/194705754-001a1ea8-4600-4c0a-a54d-e5d04ee1dfc9.png)

**Comment by vsoch** [comment]
So based on that content, don’t you think the error message is a bit strange? There is something more to it. I’m afraid I cannot help if I can’t reproduce the error - can you give me enough to reproduce?

**Comment by NirutaDhimal** [comment]
I don't know why it is deleted. I haven't touched it. I installed deid 0.2.33 version using pip. I added the clean_pixel_data in the init file.
![err4](https://user-images.githubusercontent.com/58328226/194706191-7f88d462-aa83-44a9-996b-90ac1e506a36.png)
But I got another error
![err5](https://user-images.githubusercontent.com/58328226/194706198-3f636367-6bde-426e-ba9c-e62a668b3810.png)
I think clean_pixel_data function is not present in clean.py file
I will try to run it again after I reinstall the module.

**Comment by NirutaDhimal** [comment]
Hi @vsoch Its working after I installed deid module of version 0.2.37. Thanks for helping me again. I really appreciated it :)

**Comment by vsoch** [comment]
Sure thing! If you get an error like this in the future, a good way to debug is to sanity check things - e.g., if it's telling you that you can't import something, look there to see if the function name exists (as we did). And then compare your version against the latest in version control, or if it were something else (e.g, let's say you were running things with multiprocessing) you could try the same commands in a more vanilla environment. Glad to help!
