### ISSUE TITLE
Update documentation with correct package name ("deid-data" -> "deid") 

### ISSUE THREAD

**Issue by tompollard** [pydicom/deid#236]
It looks like the package name was changed from "deid-data" to "deid" at some point. The documentation still lists the old package name ("deid-data") in places, which leads to import errors.

For example, see: https://pydicom.github.io/deid/getting-started/dicom-loading/ (rendered from https://github.com/pydicom/deid/blob/master/docs/_docs/getting-started/dicom-loading.md):

> ## Data
> 
> To run these examples, you'll need to install external deid-data.
> 
> ```bash
> $ pip install deid-data
> ```

It would be helpful to look over the documentation (and broader codebase) to replace the mentions of `deid-data` with the newer `deid-data`. I'll take a look at this sometime this week, assuming someone doesn't get there before me!

**Comment by vsoch** [comment]
Sorry I don’t follow - deid is the main package name, and deid-data is just the data component. We separated the two because the data was getting large. They are different things.

**Comment by tompollard** [comment]
Hi @vsoch, thanks for quick reply. Apologies, I'd misunderstood the relationship between the two packages and how they were intended to be used. Makes sense now, so I'll close this issue!
