### ISSUE TITLE
Tags within sequences (nested fields) are not affected by header actions

### ISSUE THREAD

**Issue by wetzelj** [pydicom/deid#243]
While working on pull request #242 it was uncovered that when the BLANK operation was being used to act on a field nested within a sequence (example:  Action: ```BLANK 00080050```  Nested Tag: ```(0040, 0275)__0__(0008, 0050)```), the index between the parent and child tag causes the [get_nested_field](https://github.com/pydicom/deid/blob/48057c4e7a903c80dfd1c17f84eba3de6d9e3fad/deid/dicom/parser.py#L121) function to return the tag incorrectly and therefore the tag within the sequence is not blanked.   This error is also currently impacting the REMOVE action. 

The get_nested_field function is only utilized in the BLANK and REMOVE actions, but I suspect that there are also issues with the other alter-type actions (JITTER and REPLACE) when acting on nested fields.  When working this issue, the full functionality of header actions on nested fields should be reviewed and additional test cases written to validate that actions on nested fields have the intended effect.

The initial discussion where this came up can be seen in this [comment](https://github.com/pydicom/deid/pull/242#discussion_r1037274578) of #242.

**Comment by vsoch** [comment]
I thought this might be related to what we were returning (e.g., parent vs the value indexed).

**Comment by vsoch** [comment]
Closed with https://github.com/pydicom/deid/pull/242
