### ISSUE TITLE
REPLACE action fails on numeric VR

### ISSUE THREAD

**Issue by wetzelj** [pydicom/deid#244]
When specifying a recipe action on header fields which are defined by numeric VRs, the action fails with an exception from pydicom during the file write operation.  

```
./test_replace_action.py::TestReplaceAction::test_replace_FD Failed with Error: With tag (0018, 9306) got exception: required argument is not a float
for data_element:
(0018, 9306) Single Collimation Width            FD: '1.3'
Traceback (most recent call last):
  File "C:\Users\wetzelj\.conda\envs\deid-core-py38\lib\site-packages\pydicom\filewriter.py", line 269, in write_numbers
    value.append
AttributeError: 'str' object has no attribute 'append'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\wetzelj\.conda\envs\deid-core-py38\lib\site-packages\pydicom\filewriter.py", line 271, in write_numbers
    fp.write(pack(format_string, value))
struct.error: required argument is not a float
```

All values are currently read in from the recipe file as string.  To write the file appropriately, pydicom requires that numeric VRs be added with values that are the correct type (due to usage of [struct.pack()](https://docs.python.org/3/library/struct.html) in [filewriter.py](https://github.com/pydicom/pydicom/blob/1db21d627e2e57dcc3aa4ec15666e71267220f62/pydicom/filewriter.py).  
Full details of the python types which can be used to set VRs can be seen [here](https://pydicom.github.io/pydicom/dev/guides/element_value_types.html). 

This issue currently impacts the following VRs:

- FD - float expected
- FL - float expected
- SL - integer expected
- SS - integer expected
- SV - integer expected
- UL - integer expected
- UN - bytes-like object expected
- US - integer expected
- UV - integer expected

This was discovered while working on #242.

**Comment by vsoch** [comment]
Closed with https://github.com/pydicom/deid/pull/242
