### ISSUE TITLE
Documentation Issue - Recipe Headers

### ISSUE THREAD

**Issue by wetzelj** [pydicom/deid#245]
Documentation added (interaction table) in the last PR looked fine when [previewed in github](https://github.com/pydicom/deid/blob/master/docs/_docs/user-docs/recipe-headers.md), but when published to the [documentation site](https://pydicom.github.io/deid/user-docs/recipe-headers/), does not render in the same manner.  

Would it be okay change the interaction table into the image below instead of building it in markdown?
![image](https://user-images.githubusercontent.com/32198293/206222855-69703d4d-07c1-441a-aed7-8d456a5dfe3b.png)

**Comment by vsoch** [comment]
Yep works for me!

**Comment by wetzelj** [comment]
Closed with #246
