### ISSUE TITLE
Circular import for config

### ISSUE THREAD

**Issue by vsoch** [pydicom/deid#247]
cc @wetzelj !

https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=624731&view=logs&j=656edd35-690f-5c53-9ba3-09c10d0bea97&t=e5c8ab1d-8ff9-5cae-b332-e15ae582ed2d

**Comment by vsoch** [comment]
I can do a quick fix.

**Comment by wetzelj** [comment]
Thank you.  I'm going take a close look at what you do to fix this so that I can learn.  It's not an area that I've dealt with, so I was poking around to figure out where the conda-forge deploy config was configured - but it wasn't immediately jumping out.

**Comment by vsoch** [comment]
If you just opened a terminal with ipython and did import deid.config it would trigger - not sure why testing didn't catch that! The fix was to have the import that you added within a function so it doesn't happen when everything inits.
