### ISSUE TITLE
Possible incorrect coordinate definition

### ISSUE THREAD

**Issue by wetzelj** [pydicom/deid#249]
While reviewing the default deid.dicom file I noticed one greylist filter entry which I believe was incorrectly changed from coordinates to ctpcoordinates.

[Stanford Medical Center LightSpeed VCT # (Roger Goldman)](https://github.com/pydicom/deid/blob/f5a53f47930aebc8f01bd04ef05d80b84006992d/deid/data/deid.dicom#L773)

If you agree, I'll submit a PR with this change.

**Comment by vsoch** [comment]
Yes looks erroneous - sorry that was likely me!

**Comment by wetzelj** [comment]
Do you want a version bump and changelog entry on this?

**Comment by vsoch** [comment]
I think this tweak would be OK to merge into main, and either we can wait for the next release (and no bumps but maybe a note) or if you think it's actively hurting someone's pipeline we can do a bump/note. Up to you!

**Comment by wetzelj** [comment]
I think it's fine to merge into main and then wait for the next release.

**Comment by vsoch** [comment]
Fixed with #250 thanks @wetzelj !
