### ISSUE TITLE
(7fe0, 0010) Pixel Data doesn't appear in the dictionary when using get_identifiers

### ISSUE THREAD

**Issue by aawez** [pydicom/deid#260]
Hi,
The PixelData attribute doesn't load in the dictionary when the get_identifiers method is used.

However, when I use pydicom.dcmread, it does appear there. 

Is this a bug, or am I missing anything? As per the [documentation page](https://pydicom.github.io/deid/getting-started/dicom-get/), PixelData should also be loaded along with other metadata tags when using get_identifiers.

**Comment by vsoch** [comment]
It's in the default config.json to skip https://github.com/pydicom/deid/blob/467b8bd76c6578683c47600b7194e3caed500fd9/deid/dicom/config.json#L4 unless you specify otherwise (change that file or do disable_skip=True).

**Comment by vsoch** [comment]
Your best bet (and for your learning) is to look into the code, specifically at the DicomParser that get_identifiers uses, and understand what it is doing (and if you want to change it). The save as will fall back to using pydicom, so any issues there should be asked to that project.

**Comment by aawez** [comment]
Thanks for your prompt response. Appreciate it!
