### ISSUE TITLE
ignoring user specified deid configuration

### ISSUE THREAD

**Issue by BrianKolowitz** [pydicom/deid#29]
If i specify a deid file, why do you append the default 'dicom' file? it overrides my preferences. for instance i'd like to specify my own patientid in my deid file, but your 'dicom' default file removes it

in my deid.dicom file i'd like to have the following override your base configuration

```
%header
REPLACE PatientID var:patient_id
```

my "fix" is in header.py
```
if deid is not None:
        # deid = load_combined_deid([deid])
        deid = get_deid(deid, load=True)
    else:
        deid = get_deid('dicom', load=True)
```

possible resolutions seem to be
a) allow the user specified configuration to override your base configuration
b) add an option that allows the user to specify if they'd like to take your base configuration in addition to what they specify

**Comment by vsoch** [comment]
This has been fixed with #30
