### ISSUE TITLE
ImportError: No module named deid.config

### ISSUE THREAD

**Issue by mobbSF** [pydicom/deid#51]
Just freshly installed via pip.
When I `from deid.config import DeidRecipe`
I get `ImportError: No module named deid.config`
Any ideas?

**Comment by vsoch** [comment]
You are probably using an old version. Do pip uninstall deid until there aren't any left, then do pip install deid, and try again. I just did this sequence of events from scratch and installed the latest version and didn't get an error.

**Comment by mobbSF** [comment]
Got it; setting up a virtual env now. Thanks.

**Comment by vsoch** [comment]
Great!
