### ISSUE TITLE
No available image handler could decode this transfer syntax JPEG Lossless, Non-Hierarchical, First-Order Prediction 

### ISSUE THREAD

**Issue by fimafurman** [pydicom/deid#64]
client.clean() threw exception: "No available image handler could decode this transfer syntax JPEG Lossless, Non-Hierarchical, First-Order Prediction"

**Comment by vsoch** [comment]
@fimafurman this responsibility is allocated to [pydicom](https://github.com/pydicom/pydicom). We are using the slightly older version, so if the newer one (with work on image handlers) can handle the syntax, then fixing here would resolve the problem! Would you be able to test your image using the latest release of pydicom to continue our discussion? If it works it will be a bit of work to update the library here, but I'm glad to do it.

**Comment by fimafurman** [comment]
Thanks - it appears their next release 1.2.0 is not yet on github and it's targeting Oct release.

**Comment by vsoch** [comment]
Ah ok! The approach I would take is to open an issue on the pydicom board, and show the version of pydicom, and the copy pasted lines (and error) for reading in your particular image. If the image is anonymized you could provide them an upload to test. That will be helpful to make sure the support is added, and the feature is passed downstream to libraries (like deid) that use pydicom.

**Comment by fimafurman** [comment]
It looks like it was created already: https://github.com/pydicom/pydicom/issues/532

**Comment by vsoch** [comment]
I’m looking over the issue and it doesn’t look like a problem with pydicom, you need to update your version of gdcm to have the libraries that are needed to support the syntax. Also look at the version of pydicom you are running for a sanity check.

**Comment by fimafurman** [comment]
Yes, it appears I did not have gdcm installed, however when I installed it, it fails to read the pixels with: UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa8 in position 24806: invalid start byte

**Comment by fimafurman** [comment]
I suspect this is related to my gdcm install, but here's another issues which might belong here:

client.save_dicom(clean_path) sometimes errors out with:
 "Pixel Data with undefined length must start with an item tag"

**Comment by vsoch** [comment]
Let's have you fix gdcm and if that errors persists, open a separate issue. Thanks.

**Comment by fimafurman** [comment]
I was able to fix gdcm by doing an anaconda install vs building from source. Will do - thank you!

**Comment by vsoch** [comment]
Some magic google searching... pydicom :) https://github.com/mrbean-bremen/pydicom/commit/469b36d9d08793c7937336a79b3c69f4052bf2b0

**Comment by fimafurman** [comment]
Yes, I saw this, but I do not fully understand what is expected. The save fails after deid replaces the region - it only seems to happen for uncompressed jpegs

**Comment by vsoch** [comment]
please if you can, provide the image, and the exact commands you issued to reproduce the issue.

**Comment by fimafurman** [comment]
I will open a new issue since this one is resolved.
