### ISSUE TITLE
Runaway temp folder appears to be leaked for every clean operation.

### ISSUE THREAD

**Issue by fimafurman** [pydicom/deid#68]
In clean.py, line 54-55 a temp folder is created and never deleted:

 if output_folder is None:
            output_folder = tempfile.mkdtemp()

The user of mkdtemp() is responsible for deleting the temporary directory and its contents when done with it.

**Comment by vsoch** [comment]
oup! looks like we need a shutil.rmtree. Give me a few minutes to look into this!

**Comment by vsoch** [comment]
Could you please show me the way you are invoking clean? If done with a general client, we can't just delete the entire folder at the end of a function call (we lose the files!) and so we would want to remove the directory given some circumstances. Let me know your calls and I'll figure out the best approach!

**Comment by vsoch** [comment]
hey @fimafurman ! I'm bad so I didn't test this, but would you care to do the honors? Here is the PR and the branch https://github.com/pydicom/deid/pull/69. The _exit__ was a good idea, but we can't be sure that the user doesn't want the folder to exist after exiting python. So instead I create the folder on init, and then remote it and only re-create it given that a save is called. In your case, it shouldn't be called so you shouldn't see the extra temporary folders created. Let me know if it works, and I can merge and upload to pypi.

**Comment by fimafurman** [comment]
I will test my workflow shortly. Thank you and your comment makes about the
destructor.

**Comment by fimafurman** [comment]
I tested my workflow and the folder is properly deleted right after creation. Not sure if there's a way to just come up with the safe name, or whether the file could be created only when needed.

**Comment by vsoch** [comment]
Yes! Let me try this, I have an idea.
