### ISSUE TITLE
Editing Dicom Preamble

### ISSUE THREAD

**Issue by Biggz1313** [pydicom/deid#72]
Hello, I'll preface that I've only been learning python since March but have come a long way. I am using Pydicom and Deid to do some mass deidentification of dicom files and I noticed when I check the files, all fields I wanted changed in the header are changing, but the Media Storage SOP Class UID and Media Storage SOP Instance UID in the preamble are not changing.  The SOP Class UID isn't that big of a deal because it's just an image type identifier, but more often than not, the Media Storage SOP Instance UID is just a copy of the actual SOP Instance UID with is PHI that needs removed.  Is there a way to alter some code to get the Deid process to also change fields in the preamble as well?  Thank you in advance for any help or guidance you can provide.

**Comment by vsoch** [comment]
Hey @Biggz1313 I can definitely look into this! I'll see if the files that I have handy are enough to test, and ping you if I might need some help to find ones. I remember the preamble was a bit tricky to deal with, so likely I missed seeing an example with PHI in the header. Stay tuned!

**Comment by Biggz1313** [comment]
Awesome!  Thank you so much for the quick response!  I see in the header.py file that there is some code about keeping preamble the same, but I get lost trying to trace back what all it's doing (it's around line 315).  Ideally I'd like to replace the MediaStorageSOPInstanceUID with the same var that I'm replacing the SOPInstanceUID with.

**Comment by vsoch** [comment]
Are you able to show me a few examples of the preambles that you see (without the PHI of course?) I want to get a sense for what winds up in there. It seems to be the case that [the field is unstructured](http://dicom.nema.org/Dicom/2013/output/chtml/part10/chapter_7.html) and not required for machines to read, so possibly we would do better to just set to the equivalent of "empty" something like the bytes `00H` ?

**Comment by vsoch** [comment]
Lord, I didn't even write this that long ago and the code looks so messy! This always happens... haha.

**Comment by Biggz1313** [comment]
Just reread one of you replies, and yes, I would be happy if the filed was just blanked.  I was just going to replace it with the SOPInstanceUID because I think most VNAs out there will use that for storage purposes so I figured if I could replace it with the value I was already creating that would be ideal, but in all honesty, if it's just blanked, I'll be happy.

**Comment by vsoch** [comment]
Okay, so if we [look here](https://pydicom.github.io/pydicom/stable/auto_examples/input_output/plot_write_dicom.html) at the creation of an "empty" preamble it's just setting it to an empty bytes string.  But I want to clarify something - the preamble is that bytes string, but what you seem to be talking about is the file meta data (with tag starting with 0002) which is different from the preamble. Is this correct? For example, here is metadata:

```bash
(0002, 0000) File Meta Information Group Length  UL: 198
(0002, 0001) File Meta Information Version       OB: b'\x00\x01'
(0002, 0002) Media Storage SOP Class UID         UI: Secondary Capture Image Storage
(0002, 0003) Media Storage SOP Instance UID      UI: xxxxxxxxxxxxxxxxxxxxxxxx
(0002, 0010) Transfer Syntax UID                 UI: JPEG Baseline (Process 1)
(0002, 0012) Implementation Class UID            UI: 1.2.276.0.7230010.3.0.3.6.1
(0002, 0013) Implementation Version Name         SH: 'OFFIS_DCMTK_361'
```
and the preamble is literally just a bytes string:

```bash
 dcm.preamble
b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
```
So you mean to say that the meta data needs some additional tweaking (and the preamble too?) Where in the above do you see the preamble?

**Comment by Biggz1313** [comment]
Sorry, yes, the meta data is what needs tweaking.  I made an incorrect assumption that the preamble contained the meta data, but I just read something that cleared that up for me after you pointed it out.  So really it's just the meta data that needs edited (specifically field (0002, 0003) ) as far as I can tell now.  Does that make it easier?

**Comment by vsoch** [comment]
Yes definitely clear! It looks like the 0002 header fields are used for easier reading, see :point_right:  https://stackoverflow.com/questions/32689446/is-it-true-that-dicom-media-storage-sop-instance-uid-sop-instance-uid-why What I can do is to modify the code to blank it, and then give you a branch to test. We would want to see if any of your viewers have issue with opening the file, etc. Give me a few minutes and I'll put together something to test!

**Comment by Biggz1313** [comment]
that would be fantastic, thank you!

**Comment by vsoch** [comment]
okay I'm done, but I'm taking a few more minutes to clean up the docstrings because it will drive me nuts if I don't :P

**Comment by vsoch** [comment]
@Biggz1313 see https://github.com/pydicom/deid/pull/73 I'll be afk for a bit, but back after you've had a chance to test. Notes for the PR are in the description. Hopefully it's a step in the right direction!

**Comment by vsoch** [comment]
Changes released with https://pypi.org/project/deid/0.1.19/
