### ISSUE TITLE
pydicom.read_file() --> _get_pixel_array() no longer exists

### ISSUE THREAD

**Issue by howardpchen** [pydicom/deid#83]
Attempting to use the DicomCleaner class to do pixel-level cleaning.

Looks like I keep getting an error in the `clean.py` file:

> <ipython-input-41-aa448e009737> in <module>
>       5     print(out)
>       6     if out['flagged']:
> ----> 7         client.clean()
> 
> /opt/conda/lib/python3.6/site-packages/deid-0.1.23-py3.6.egg/deid/dicom/pixels/clean.py in clean(self)
>     106 
>     107             # We will set original image to image, cleaned to clean
> --> 108             self.original = dicom._get_pixel_array()
>     109             self.cleaned = self.original.copy()
>     110 
> 
> /opt/conda/lib/python3.6/site-packages/pydicom/dataset.py in __getattr__(self, name)
>     530         if tag is None:  # `name` isn't a DICOM element keyword
>     531             # Try the base class attribute getter (fix for issue 332)
> --> 532             return super(Dataset, self).__getattribute__(name)
>     533         tag = Tag(tag)
>     534         if tag not in self.tags:  # DICOM DataElement not in the Dataset
> 
> AttributeError: 'FileDataset' object has no attribute '_get_pixel_array'

Tracing this issue back it looks like pydicom's FileDataset doesn't actually have a _get_pixel_array() function, as follows:

> from pydicom import read_file
> dicom = read_file(dicom_files[0])
> dicom._get_pixel_array()

(dicom_files is a list of local paths to DICOM files). Gives the same error at the same location:

> AttributeError                            Traceback (most recent call last)
> <ipython-input-51-f7f42af5b358> in <module>
>       1 from pydicom import read_file
>       2 dicom = read_file(dicom_files[0])
> ----> 3 dicom._get_pixel_array()
> 
> /opt/conda/lib/python3.6/site-packages/pydicom/dataset.py in __getattr__(self, name)
>     530         if tag is None:  # `name` isn't a DICOM element keyword
>     531             # Try the base class attribute getter (fix for issue 332)
> --> 532             return super(Dataset, self).__getattribute__(name)
>     533         tag = Tag(tag)
>     534         if tag not in self.tags:  # DICOM DataElement not in the Dataset
> 
> AttributeError: 'FileDataset' object has no attribute '_get_pixel_array'

On the other hand, I seem to be able to call for the variable directly using `dicom.pixel_array` or, alternatively, `dicom.__getattribute__("pixel_array")`

Maybe pydicom changed the Dataset class at some point and broke the `clean.py` implementation?

**Comment by vsoch** [comment]
Deid hasn’t been updated to what was previously a release candidate and now the official release on master of pydicom.  If you downgrade the issue will be resolved and the larger fix needs to be to update the entire package, which is a large amount of work.

**Comment by vsoch** [comment]
hey @howardpchen could you please test with `pydicom==1.1.0` ? We can have the freeze to that version as a quick fix. If it's the case that I had installed 1.1.0 when it was a release candidate then you will likely get the same issue (and please let me know).

**Comment by howardpchen** [comment]
Yes confirmed. I locked pydicom to 1.1.0 and it works fine. Did the same with the Docker bersion by setting `pip install pydicom==1.1` in the Dockerfile and it works as well.

**Comment by vsoch** [comment]
Great! I'll get in a PR to fix this soon, unless you would like to open one? In the future, if you file an issue and are able to help the maintainer by providing your suggested solution, you should do this. Other users are likely to run into the same issue so it's in the best interest to find a solution quickly! And I happen to know the issue this time, but I can assure you there are many more things I don't know than know :P

**Comment by vsoch** [comment]
Please review --> https://github.com/pydicom/deid/pull/84

**Comment by howardpchen** [comment]
Vanessa thanks for the recommendation! In all honesty I've not thought about it till now because it always feels like I might just not be using the package right instead of a bug.  Thanks for the encouragement and will recommend pull requests for basic fixes here on out!

**Comment by vsoch** [comment]
Awesome! It's definitely the user base that drives development and I'm extremely grateful for catching all these :bug:. If you have time to do a PR, that's even better. But if not? That's what I'm here for! :avocado:
