### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by BLT81** [pydicom/deid#97]
I'm getting error while installing from pypi. Have you seen this before?

$ python -m pip install deid
Requirement already satisfied: deid in c:\users\trumpb\appdata\local\programs\python\python37\lib\deid (0.1.31)
Collecting matplotlib<=2.1.2 (from deid)
  Using cached https://files.pythonhosted.org/packages/6d/bd/3e8cec37bcf71cfd81fe798cf733c046b1ceb123e7dddf6d3435cf03b506/matplotlib-2.1.2.tar.gz
    Complete output from command python setup.py egg_info:
    ============================================================================
    Edit setup.cfg to change the build options

    BUILDING MATPLOTLIB
                matplotlib: yes [2.1.2]
                    python: yes [3.7.2 (tags/v3.7.2:9a3ffc0492, Dec 23 2018,
                            23:09:28) [MSC v.1916 64 bit (AMD64)]]
                  platform: yes [win32]

    REQUIRED DEPENDENCIES AND EXTENSIONS
                     numpy: yes [version 1.15.4]
                       six: yes [using six version 1.12.0]
                  dateutil: yes [using dateutil version 2.7.5]
    backports.functools_lru_cache: yes [Not required]
              subprocess32: yes [Not required]
                      pytz: yes [pytz was not found. pip/easy_install may
                            attempt to install it after matplotlib.]
                    cycler: yes [using cycler version 0.10.0]
                   tornado: yes [tornado was not found. It is required for the
                            WebAgg backend. pip/easy_install may attempt to
                            install it after matplotlib.]
                 pyparsing: yes [using pyparsing version 2.3.0]
                    libagg: yes [pkg-config information for 'libagg' could not
                            be found. Using local copy.]
                  freetype: no  [The C/C++ header for freetype
                            (freetype2\ft2build.h) could not be found.  You may
                            need to install the development package.]
                       png: no  [The C/C++ header for png (png.h) could not be
                            found.  You may need to install the development
                            package.]
                     qhull: yes [pkg-config information for 'libqhull' could not
                            be found. Using local copy.]

    OPTIONAL SUBPACKAGES
               sample_data: yes [installing]
                  toolkits: yes [installing]
                     tests: no  [skipping due to configuration]
            toolkits_tests: no  [skipping due to configuration]

    OPTIONAL BACKEND EXTENSIONS
                    macosx: no  [Mac OS-X only]
                    qt5agg: no  [PySide2 not found; PyQt5 not found]
                    qt4agg: no  [PySide not found; PyQt4 not found]
                   gtk3agg: no  [Requires pygobject to be installed.]
                 gtk3cairo: no  [Requires cairocffi or pycairo to be installed.]
                    gtkagg: no  [Requires pygtk]
                     tkagg: yes [installing; run-time loading from Python Tcl /
                            Tk]
                     wxagg: no  [requires wxPython]
                       gtk: no  [Requires pygtk]
                       agg: yes [installing]
                     cairo: no  [cairocffi or pycairo not found]
                 windowing: yes [installing]

    OPTIONAL LATEX DEPENDENCIES
                    dvipng: no
               ghostscript: no
                     latex: no
                   pdftops: no

    OPTIONAL PACKAGE DATA
                      dlls: no  [skipping due to configuration]

    ============================================================================
                            * The following required packages can not be built:
                            * freetype, png * Please check http://gnuwin32.sourc
                            * eforge.net/packages/freetype.htm for instructions
                            * to install freetype * Please check http://gnuwin32
                            * .sourceforge.net/packages/libpng.htm for
                            * instructions to install png

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\trumpb\AppData\Local\Temp\pip-install-1p5uhnra\matplotlib\

**Comment by vsoch** [comment]
Yes I have! pip won't install missing dependencies  on your system (like lib freetype) so you should install them first. I found the same issue [here](https://stackoverflow.com/questions/20533426/ubuntu-running-pip-install-gives-error-the-following-required-packages-can-no) that shows the different libraries that are available with apt-get. Let me know if that works for you!

**Comment by vsoch** [comment]
hey @BLT81 was this resolved for you?

**Comment by BLT81** [comment]
Hi Vanessa,


I'm unsure at this point. I successfully installed those dependencies but I am still getting the error when attempting to install. It could be a bug somewhere else.


Thanks,

Brad


________________________________

**Comment by BLT81** [comment]
I installed LibPng and freetype using Gnuwin installers for Windows.  I will attempt to try it with Anaconda

**Comment by BLT81** [comment]
I reinstalled freetype and then used Anaconda to install DEID. It was successful. However, it failed when trying to install with a windows prompt. I'm wondering why it works in Anaconda but not outside. Wouldn't it be using the same lib png and freetype?

**Comment by vsoch** [comment]
I think the reason is (likely) because you installed the core libraries for freetype and png, but not the development libraries. I'm not sure what this looks like in Windows, but in Ubuntu the difference usually comes down to installing something like `libfreetype` *and* `libfreetype-dev`. When you install with Anaconda, it likely installs the needed development libraries.

**Comment by vsoch** [comment]
I'm closing this issue, the user was missing libraries (and I'm not sure how deid could have been installed from Anaconda, because I just added it yesterday).

**Comment by BLT81** [comment]
I abandoned trying to fix this issue. It is also quite easy to install non-conda packages with anaconda. https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-pkgs.html#installing-non-conda-packages

**Comment by vsoch** [comment]
The reason it worked for Anaconda but "not outside" is because Anaconda maintains these libraries [for you](https://stackoverflow.com/questions/42348726/where-is-mkl-or-other-libraries-located-in-an-anaconda-installation). When you installed using it, it handled it. The error on your regular system for Matplotlib is because you did not have the development libraries, or you installed them but didn't properly add them to the path. Best of luck!
