### ISSUE TITLE
notContains not expecting a field?

### ISSUE THREAD

**Issue by fimafurman** [pydicom/deid#98]
I had to use 'notContains' clause in deid rules and expected it to work just like contains clause with the opposite effect, however, I found that the parser does not actually expect the value to be present. It looks like a bug, as notcontains should expect a field value:

In utils.py:

`# Missing, empty, notcontains expect only a field
 elif action in ['missing', 'empty','notcontains', 'present']:
       field = member.strip()`

**Comment by fimafurman** [comment]
Yes, I verified that moving ''notcontains' to the field expecting condition fixes this issue:

 if action in ['contains','equals','notequals','notcontains']:

**Comment by vsoch** [comment]
Thanks @fimafurman I'll get this fixed up soon.
